### PR TITLE
Simulated varicella outbreak to compute incidence rates

### PR DESCRIPTION
**Pull request by jakobschumacher**
This pull request includes a data file with which one can compute incidence rates

### CODE REVIEW

**Comment by jakobschumacher** [comment]
Thanks for the suggestions.

**Comment by zkamvar** [comment]
I'm going to post the conversation we had on Slack for clarification and to add my own comments:

From @finlaycampbell:

> Hi Jakob, thanks for the pull request! A couple things to note:
>
> - Could you fix the first four column names (they currently all have `name.` in front of them, which we don't need)
> - could you put a brief description of what each column represents, like in this example:
> ```r
> #' @format {
> #' A data frame with 57 rows and 3 columns
> #' \describe{
> #'   \item{onset_date}{Date}
> #'   \item{nr}{Days after starting date}
> #'   \item{value}{Number of cases}
> #' }
> ```
> 
> With regards to the code you use to simulate the data, it would be best if it was readily available for people to run themselves, without it being locked away in the documentation. I don't think the `outbreaks` package itself is the right place to keep it, as it's not intended as a code repository. Perhaps the best approach would be for you to make the code available on your own github repo, which we can then link to in the documentation? @zkamvar do you have any thoughts on this?
>
> Once we iron these issues out we can hopefully merge your PR

Regarding making the code available: I think that, given the fact that this data is *easily* simulated in R, it makes complete sense to include it. I agree with @finlaycampbell that it doesn't belong in the description section of the documentation, but don't see why it can't be included in the example section.

To include it in the example section, we would need to place the [randomNames package](https://cran.r-project.org/package=randomNames) in the `Suggests` field of the DESCRIPTION file. This won't affect the reverse dependencies of outbreaks since suggested packages of dependencies don't get installed by default.

It would also be good to include a small example at the beginning of how to calculate incidence rate.

Let me know if I'm stepping out of my bounds, @finlaycampbell.

**Comment by finlaycampbell** [comment]
Thanks for the changes, Jakob! That's looking very good. One last thing - you've got two `varicella_sim_berlin.RData` files in the `\data` folder at the moment. If you can delete the old one, and add a very short example showing how you can calculate the incidence rate as @zkamvar mentioned, I think we should be ready to merge.

Not overstepping at all @zkamvar! I think the code used to simulate the data is just long enough to deserve it's own repo, and also allows Jakob to develop it in the future (if he would so wish) without having to refer back to us. Generally I'd like to keep `outbreaks` as purely a data repository - though going forward it would be very nice to have a separate package that provides code for simulating outbreak data (perhaps calling on the work done at [epirecipes](http://epirecip.es/epicookbook/)).

**Comment by jakobschumacher** [comment]
Hi, i deleted the old version of the dataset. I agree that an example would be great, but the best thing would be to be able to do that with a new function in the incidence package. So I'll try to include an example later.

**Comment by finlaycampbell** [comment]
OK all merged now, thanks again! If you do end up writing an example just make another PR.

**Pull request merged**
